squirleHP - 44;
squirleNum - 7;
squirleType - "Water";
squirleBestMove - "Bite";
squirleLastEvo - Blastoise
squirleAttack - 48;
squirleDefense - 65;
squirleBaseEXP - 66;
squirleEggCycles - 20;
squirleCatchRate - 45;